"""empty message

Revision ID: a066f06c3a3b
Revises: 6d0092929de1
Create Date: 2024-07-25 01:04:47.295155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a066f06c3a3b'
down_revision = '6d0092929de1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profesor', schema=None) as batch_op:
        batch_op.alter_column('contrasena',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profesor', schema=None) as batch_op:
        batch_op.alter_column('contrasena',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)

    # ### end Alembic commands ###
