"""empty message

Revision ID: c35f0603268e
Revises: a1a402fe678e
Create Date: 2024-07-26 21:06:22.417254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c35f0603268e'
down_revision = 'a1a402fe678e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apoderado', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rol', sa.String(length=120), nullable=False))
        batch_op.alter_column('contrasena',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=255),
               existing_nullable=False)

    with op.batch_alter_table('profesor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rol', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profesor', schema=None) as batch_op:
        batch_op.drop_column('rol')

    with op.batch_alter_table('apoderado', schema=None) as batch_op:
        batch_op.alter_column('contrasena',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
        batch_op.drop_column('rol')

    # ### end Alembic commands ###
